apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    name: eureka-server
spec:
  ports:
    - port: 80
      targetPort: 8761
      protocol: TCP
  selector:
    app: eureka-server
  type: LoadBalancer
